# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bactracking_Solutiion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_size', models.IntegerField(default=0)),
                ('solution_cost', models.FloatField(default=0.0)),
                ('coordinates', models.CharField(max_length=100000)),
                ('expanded_nodes', models.IntegerField(default=0)),
                ('excecution_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
