# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artificial_intelligence', '0002_auto_20160831_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bactracking_solution',
            old_name='excecution_time',
            new_name='execution_time',
        ),
    ]
