# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artificial_intelligence', '0003_auto_20160831_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='bactracking_solution',
            name='nodes',
            field=models.IntegerField(default=0),
        ),
    ]
