# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artificial_intelligence', '0004_bactracking_solution_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSP_Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_size', models.IntegerField(default=0)),
                ('solution_cost', models.FloatField(default=0.0)),
                ('coordinates', models.CharField(max_length=100000)),
                ('expanded_nodes', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('nodes', models.IntegerField(default=0)),
                ('approach', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Bactracking_Solution',
        ),
    ]
